### ISSUE TITLE
NetSock_Accept may release globalLock but not Acquire it

### ISSUE THREAD

**Issue by jameszxj** [SiliconLabs/uC-TCP-IP#1] opened 2020-04-18 11:26 UTC
In function NetSock_Accept()，when check Validate initial addr len (line:4554-4588) error, the function
exit with Net_GlobalLockRelease() from label exit_err_acccept，but the function did not call Net_GlobalLockAcquire() before.

**Comment by yasosa305** [comment] 2020-04-30 18:54
Thanks, jameszxj

This yields no functional issues but it will be addressed.

**Comment by wes-jmagasrevy** [comment] 2021-05-21 19:18
Duplicate of https://github.com/weston-embedded/uC-TCP-IP/issues/13

**Closed as completed by wes-jmagasrevy** 2021-05-21 19:18 UTC
